import { TutorialStep } from './TutorialOverlay'

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Careersy Wingman! 👋',
    description: 'Your AI-powered career coach for the ANZ tech market. Let\'s take a quick tour of the features that will help you land your dream tech role.',
    position: 'center',
    action: 'view',
  },
  {
    id: 'send-message',
    title: 'Chat with Your Career Coach',
    description: 'Ask anything about your tech career - resume reviews, interview prep, salary negotiation, or job search strategies. Just type and hit send!',
    targetSelector: 'input[type="text"][placeholder="|"]',
    position: 'top',
    action: 'type',
  },
  {
    id: 'add-context',
    title: 'Add Context',
    description: 'Click this button to upload your resume, job descriptions, or LinkedIn profile. Try clicking it now!',
    targetSelector: 'button[type="button"]:has(svg path[d*="M12 4v16m8-8H4"]):first-of-type',
    resultSelector: 'div[class*="fixed"][class*="inset-0"]:has(textarea)',
    position: 'top',
    action: 'click',
    allowInteraction: true,
    waitForElement: true,
  },
  {
    id: 'chat-history',
    title: 'View Chat History',
    description: 'Click the hamburger menu to see all your past conversations. Go ahead, try it!',
    targetSelector: 'button:has(svg path[d*="M4 6h16M4 12h16M4 18h16"])',
    resultSelector: 'div.w-64.bg-white',
    position: 'right',
    action: 'click',
    allowInteraction: true,
    waitForElement: true,
  },
  {
    id: 'collaborate-toggle',
    title: 'Collaborate Mode',
    description: 'Toggle this to share conversations publicly with the Careersy community. Get feedback from peers and see how others approach similar challenges!',
    targetSelector: 'button:has(span[class*="rounded-full"][class*="bg-"])',
    position: 'left',
    action: 'view',
  },
  {
    id: 'add-conversation',
    title: 'Start New Public Conversation',
    description: 'When in Collaborate mode, use this to create a new public thread with a custom title. Perfect for asking the community questions!',
    targetSelector: 'button:has(svg path[d*="M12 4v16m8-8H4"])',
    position: 'bottom',
    action: 'view',
  },
  {
    id: 'search-conversations',
    title: 'Search Conversations',
    description: 'In Collaborate mode, search through community conversations to find relevant discussions, resume examples, or interview tips.',
    targetSelector: 'button:has(svg path[d*="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"])',
    position: 'bottom',
    action: 'view',
  },
  {
    id: 'logout',
    title: 'Account Settings',
    description: 'Find your logout button and account details in the sidebar at the bottom. Your conversations are always saved and synced.',
    targetSelector: 'button:has(span:contains("Logout"))',
    position: 'right',
    action: 'view',
  },
  {
    id: 'ready',
    title: 'You\'re All Set! 🚀',
    description: 'Start chatting to level up your ANZ tech career. Get personalized resume reviews, interview prep, salary insights, and job search strategies. Good luck!',
    position: 'center',
    action: 'view',
  },
]
